package configtx

import (
	"context"
	"sync"

	"github.com/galendai/homepi-mon/internal/secretstore"
)

// overlayStore is an in-memory secretstore.Store used during draft
// testing. It is keyed by canonical ref name and never touches disk or
// the OS keyring. The fallback backing store is consulted on cache
// miss, so the overlay can also be used to inject a candidate secret
// while still letting other refs resolve normally.
type overlayStore struct {
	mu     sync.RWMutex
	values map[string]string
	// fallback is consulted for keys the overlay does not carry. It
	// may be nil, in which case unknown keys return ErrNotFound.
	fallback secretstore.Store
}

func newOverlayStore(fallback secretstore.Store) *overlayStore {
	return &overlayStore{
		values:   make(map[string]string),
		fallback: fallback,
	}
}

func (o *overlayStore) Backend() string {
	if o.fallback != nil {
		return "overlay+" + o.fallback.Backend()
	}
	return "overlay"
}

func (o *overlayStore) Get(_ context.Context, ref string) (string, error) {
	o.mu.RLock()
	v, ok := o.values[ref]
	o.mu.RUnlock()
	if ok {
		return v, nil
	}
	if o.fallback != nil {
		return o.fallback.Get(context.Background(), ref)
	}
	return "", secretstore.ErrNotFound
}

func (o *overlayStore) Set(_ context.Context, ref, value string) error {
	if err := secretstore.ValidateRef(ref); err != nil {
		return err
	}
	o.mu.Lock()
	defer o.mu.Unlock()
	o.values[ref] = value
	return nil
}

func (o *overlayStore) Delete(_ context.Context, ref string) error {
	o.mu.Lock()
	defer o.mu.Unlock()
	if _, ok := o.values[ref]; !ok {
		return secretstore.ErrNotFound
	}
	delete(o.values, ref)
	return nil
}

// has reports whether the overlay has a value for ref without
// falling back. Useful for the draft "candidate secret pending" state.
func (o *overlayStore) has(ref string) bool {
	o.mu.RLock()
	defer o.mu.RUnlock()
	_, ok := o.values[ref]
	return ok
}

// snapshot returns a copy of the overlay values for audit logging.
// The copy never includes secret values, only refs and presence
// booleans, so audit summaries can be written without leaking.
func (o *overlayStore) snapshot() map[string]bool {
	o.mu.RLock()
	defer o.mu.RUnlock()
	out := make(map[string]bool, len(o.values))
	for k := range o.values {
		out[k] = true
	}
	return out
}

// snapshotValues returns a copy of the overlay's (ref, value) pairs.
// The Apply pipeline uses it to commit candidate secrets to the
// real keyring; the Web Admin and audit summaries never read it
// because secret values are not allowed outside the server process.
func (o *overlayStore) snapshotValues() map[string]string {
	o.mu.RLock()
	defer o.mu.RUnlock()
	out := make(map[string]string, len(o.values))
	for k, v := range o.values {
		out[k] = v
	}
	return out
}

// deleteFor removes any overlay value whose ref name contains the
// given provider id. The match is intentionally loose because the
// overlay key always starts with the provider id when generated by
// the draft flow. It is a no-op when nothing matches.
func (o *overlayStore) deleteFor(providerID string) {
	if providerID == "" {
		return
	}
	o.mu.Lock()
	defer o.mu.Unlock()
	for k := range o.values {
		if containsProviderID(k, providerID) {
			delete(o.values, k)
		}
	}
}

// containsProviderID matches refs shaped as keyring:provider-key:<id>
// or keyring:provider-key:<id>@<n> (the rotated variant). It is not a
// general-purpose substring match.
func containsProviderID(ref, providerID string) bool {
	const prefix = "keyring:provider-key:"
	if len(ref) <= len(prefix) {
		return false
	}
	rest := ref[len(prefix):]
	if at := indexAt(rest); at >= 0 {
		rest = rest[:at]
	}
	return rest == providerID
}

func indexAt(s string) int {
	for i := 0; i < len(s); i++ {
		if s[i] == '@' {
			return i
		}
	}
	return -1
}
